version: '3.9'
services:
  neovim:
    build: .
    tty: true # create a tty to keep the container running until it gets manually terminated
              # Does not work if we run "command:".
    command:
      - /bin/sh
      - -c
      - |
          echo "This container will copy your .ssh/id_rsa file into the container."
          echo "foo1"
          mkdir -p ~/.ssh/
          cp /run/secrets/id_rsa ~/.ssh/id_rsa
          
          # Clone my dotfiles. As we do not check if the key is correct this is vulnerable to man 
          # in the middle attacks.
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cd /root 
          git clone git@github.com:tijoer/dotfiles.git
          cd dotfiles 
          git checkout new
          # chmod +x setupNewPi.sh 
          #./setupNewPi.sh
          #
          # We want this container to stay open after it is started. An easy way is
          # to start a bash and do nothing with this. If we delete this line the container
          # will close after it is started. If we do not run the "command:" part of this yml
          # file the container will stay open because of the "tty: true" line. But as we are
          # running commands we need to open a shell as an easy fix.
          /bin/bash
    stdin_open: true
    secrets:
      - id_rsa # The secret can be found under /run/secrets/id_rsa in the running container.

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa

